version: '3.11'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./config/.env
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:latest
    restart: always
    # volumes:
    #   - data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  data:
