# Generated by Django 5.0 on 2023-12-27 15:23

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_alt',
            field=models.CharField(blank=True, help_text='text to be loaded in case of image loss', max_length=200, null=True, verbose_name='photo_alt'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_profile',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo_profile'),
        ),
        migrations.AddField(
            model_name='volunteerinfo',
            name='phone_number',
            field=models.CharField(blank=True, help_text='The phone number must be in the format: "+380999999999"', max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='The phone number must be in the format: "+380999999999". Starts with "+380" and 9 digits.', regex='^\\+380\\d{9}')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='volunteerinfo',
            name='user',
            field=models.OneToOneField(help_text='the user that the volunteer belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
