# Generated by Django 5.0 on 2023-12-26 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerinfo',
            name='last_name',
            field=models.CharField(help_text='last name of the user', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='last name'),
        ),
    ]
