# Generated by Django 5.0 on 2024-01-03 11:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_photo_alt_user_photo_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerinfo',
            name='active',
            field=models.BooleanField(default=False, help_text='Active volunteer account or not', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='volunteerinfo',
            name='additional_info',
            field=models.TextField(blank=True, help_text="Description of the volunteer's activities", verbose_name='additional info'),
        ),
        migrations.AlterField(
            model_name='volunteerinfo',
            name='first_name',
            field=models.CharField(help_text='First name of the user', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='volunteerinfo',
            name='last_name',
            field=models.CharField(help_text='Last name of the user', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='volunteerinfo',
            name='public_name',
            field=models.CharField(help_text='For display in donations and publication in articles', max_length=150, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='public name'),
        ),
        migrations.AlterField(
            model_name='volunteerinfo',
            name='user',
            field=models.OneToOneField(help_text='The user that the volunteer belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
