# Generated by Django 5.0 on 2024-01-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_volunteerinfo_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photo_alt',
            new_name='img_alt',
        ),
    ]
