# Generated by Django 5.0 on 2023-12-28 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JarTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of tag', max_length=50, validators=[django.core.validators.MinValueValidator(2)], verbose_name='name')),
            ],
            options={
                'verbose_name': 'jar tag',
                'verbose_name_plural': 'jar tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Jar',
            fields=[
                ('monobank_id', models.CharField(help_text='ID of monobank jar', max_length=31, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10)], verbose_name='jar id')),
                ('title', models.CharField(help_text='Name of jar specified by user', max_length=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='jar name')),
                ('goal', models.IntegerField(blank=True, help_text='A goal sum of jar', null=True, validators=[django.core.validators.MinValueValidator(0, "Value can't be less than 0")], verbose_name='goal')),
                ('current', models.IntegerField(blank=True, help_text='A current sum in jar', null=True, validators=[django.core.validators.MinValueValidator(0, "Value can't be less than 0")], verbose_name='current')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='jars.jartag')),
            ],
            options={
                'verbose_name': 'jar',
                'verbose_name_plural': 'jars',
                'ordering': ['-date_added', 'current'],
            },
        ),
    ]
