# Generated by Django 5.0 on 2024-01-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jar',
            options={'ordering': ['dd_order', '-date_added'], 'verbose_name': 'jar', 'verbose_name_plural': 'jars'},
        ),
        migrations.AddField(
            model_name='jar',
            name='dd_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
