# Generated by Django 5.0 on 2023-12-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jar',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
