# Generated by Django 5.0 on 2023-12-28 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jar',
            name='date_closed',
            field=models.DateTimeField(blank=True, help_text='The date and time when goal sum in jar was reached.', null=True, verbose_name='date closed'),
        ),
        migrations.AlterField(
            model_name='jar',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when jar was added to website.', verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='jar',
            name='monobank_id',
            field=models.CharField(help_text='ID of monobank jar', max_length=31, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='jar id'),
        ),
        migrations.AlterField(
            model_name='jar',
            name='title',
            field=models.CharField(help_text='Name of jar specified by user', max_length=50, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='jar name'),
        ),
        migrations.AlterField(
            model_name='jartag',
            name='name',
            field=models.CharField(help_text='The name of tag', max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='name'),
        ),
    ]
