# Generated by Django 5.0 on 2024-01-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0002_alter_jar_options_jar_dd_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jar',
            options={'ordering': ['-date_added'], 'verbose_name': 'jar', 'verbose_name_plural': 'jars'},
        ),
    ]
