# Generated by Django 5.0 on 2024-01-03 18:19

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0003_alter_jar_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jar',
            name='active',
        ),
        migrations.AddField(
            model_name='jar',
            name='img_alt',
            field=models.CharField(blank=True, help_text='text to be loaded in case of image loss', max_length=200, null=True, verbose_name='img_alt'),
        ),
        migrations.AddField(
            model_name='jar',
            name='title_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='title_img'),
        ),
        migrations.AlterField(
            model_name='jar',
            name='date_closed',
            field=models.DateTimeField(blank=True, default=None, help_text='The date and time when goal sum in jar was reached.', null=True, verbose_name='date closed'),
        ),
        migrations.CreateModel(
            name='JarAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='img')),
                ('img_alt', models.CharField(blank=True, help_text='text to be loaded in case of image loss', max_length=200, null=True, verbose_name='img_alt')),
                ('date_added', models.DateField(auto_now=True, verbose_name='date added')),
                ('jar', models.ForeignKey(help_text='The jar that the jar album belongs to', on_delete=django.db.models.deletion.CASCADE, to='jars.jar', verbose_name='jar')),
            ],
            options={
                'verbose_name': 'jar album',
                'verbose_name_plural': 'Albums of jars',
                'ordering': ['-date_added'],
            },
        ),
    ]
