# Generated by Django 5.0 on 2024-01-05 11:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0004_remove_jar_active_jar_img_alt_jar_title_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jar',
            options={'ordering': ['-date_added'], 'verbose_name': 'jar', 'verbose_name_plural': 'Jars'},
        ),
        migrations.AlterModelOptions(
            name='jartag',
            options={'ordering': ['name'], 'verbose_name': 'jar tag', 'verbose_name_plural': 'Jar Tags'},
        ),
        migrations.AlterField(
            model_name='jar',
            name='goal',
            field=models.PositiveIntegerField(blank=True, help_text='A goal sum of jar', null=True, verbose_name='goal'),
        ),
        migrations.AlterField(
            model_name='jar',
            name='monobank_id',
            field=models.CharField(help_text='ID of monobank jar', max_length=31, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='monobank jar id'),
        ),
        migrations.AlterField(
            model_name='jar',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for Jar', to='jars.jartag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='jaralbum',
            name='jar',
            field=models.ForeignKey(help_text='The Jar that the images of JarAlbum belongs to', on_delete=django.db.models.deletion.CASCADE, to='jars.jar', verbose_name='jar'),
        ),
        migrations.CreateModel(
            name='AmountOfJar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.PositiveIntegerField(blank=True, help_text='A current sum in jar', null=True, verbose_name='sum')),
                ('date_added', models.DateField(auto_now_add=True, help_text='The date and time when sum was added.', verbose_name='date added')),
                ('jar', models.ForeignKey(help_text='The Jar that the AmountOfJar belongs to', on_delete=django.db.models.deletion.CASCADE, to='jars.jar', verbose_name='jar id')),
            ],
            options={
                'verbose_name': 'amount of jar',
                'verbose_name_plural': 'Amounts Of Jars',
                'ordering': ['jar', '-date_added'],
            },
        ),
        migrations.DeleteModel(
            name='JarCurrentSum',
        ),
    ]
