# Generated by Django 5.0 on 2024-01-08 08:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0007_alter_jar_title_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jaralbum',
            options={'ordering': ['date_added'], 'verbose_name': 'jar album', 'verbose_name_plural': 'Albums of jars'},
        ),
        migrations.AddField(
            model_name='jar',
            name='description',
            field=models.TextField(default='Description for jar', help_text='Description for jar', validators=[django.core.validators.MinLengthValidator(50)], verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amountofjar',
            name='jar',
            field=models.ForeignKey(help_text='The Jar that the AmountOfJar belongs to', on_delete=django.db.models.deletion.CASCADE, to='jars.jar', verbose_name='jar'),
        ),
        migrations.AlterField(
            model_name='jar',
            name='img_alt',
            field=models.CharField(blank=True, help_text='Text to be loaded in case of image loss', max_length=200, null=True, verbose_name='img_alt'),
        ),
    ]
