# Generated by Django 5.0 on 2024-01-12 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0008_alter_jaralbum_options_jar_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jar',
            name='monobank_id',
            field=models.CharField(help_text='ID of monobank jar', max_length=31, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='monobank jar id'),
        ),
    ]
