# Generated by Django 5.0 on 2024-01-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0009_alter_jar_monobank_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountofjar',
            name='incomes',
            field=models.PositiveIntegerField(blank=True, help_text='Amount of incomes', null=True, verbose_name='incomes'),
        ),
    ]
