# Generated by Django 5.0 on 2024-01-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jars', '0011_alter_amountofjar_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountofjar',
            name='incomes',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Amount of incomes', verbose_name='incomes'),
        ),
    ]
